Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 6
Rules claiming more threads will be scaled down.
Singularity containers: ignored
Job counts:
	count	jobs
	1	align_mni_rigid
	1	all
	32	coarseTrain
	64	featureExtract_coarse
	1	fid_tform_mni_rigid
	1	fsl_to_ras
	100

[Sun Jul 26 22:42:56 2020]
rule featureExtract_coarse:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-04_sub-0086_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-04_sub-0086_registration.done
    jobid: 38
    wildcards: afid_num=04_sub-0086

[Sun Jul 26 22:42:56 2020]
rule featureExtract_coarse:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-11_sub-0086_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-11_sub-0086_registration.done
    jobid: 45
    wildcards: afid_num=11_sub-0086

[Sun Jul 26 22:42:56 2020]
rule featureExtract_coarse:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-19_sub-0086_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-19_sub-0086_registration.done
    jobid: 53
    wildcards: afid_num=19_sub-0086

[Sun Jul 26 22:42:56 2020]
rule featureExtract_coarse:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-26_sub-0086_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-26_sub-0086_registration.done
    jobid: 60
    wildcards: afid_num=26_sub-0086

[Sun Jul 26 22:42:56 2020]
rule featureExtract_coarse:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-02_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-02_registration.done
    jobid: 102
    wildcards: afid_num=02

[Sun Jul 26 22:42:56 2020]
rule featureExtract_coarse:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-10_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-10_registration.done
    jobid: 110
    wildcards: afid_num=10

[Sun Jul 26 22:42:57 2020]
Error in rule featureExtract_coarse:
    jobid: 38
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-04_sub-0086_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-04_sub-0086_registration.done

RuleException:
CalledProcessError in line 63 of /home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/.snakemake/scripts/tmpl799vx3z.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk", line 63, in __rule_featureExtract_coarse
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Sun Jul 26 22:42:57 2020]
Error in rule featureExtract_coarse:
    jobid: 102
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-02_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-02_registration.done

RuleException:
CalledProcessError in line 63 of /home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/.snakemake/scripts/tmpse7pxnl_.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk", line 63, in __rule_featureExtract_coarse
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Sun Jul 26 22:42:57 2020]
Error in rule featureExtract_coarse:
    jobid: 45
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-11_sub-0086_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-11_sub-0086_registration.done

RuleException:
CalledProcessError in line 63 of /home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/.snakemake/scripts/tmpgh3dta8f.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk", line 63, in __rule_featureExtract_coarse
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Sun Jul 26 22:42:57 2020]
Error in rule featureExtract_coarse:
    jobid: 110
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-10_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-10_registration.done

RuleException:
CalledProcessError in line 63 of /home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/.snakemake/scripts/tmpdssn8fnh.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk", line 63, in __rule_featureExtract_coarse
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Sun Jul 26 22:42:57 2020]
Error in rule featureExtract_coarse:
    jobid: 60
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-26_sub-0086_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-26_sub-0086_registration.done
[Sun Jul 26 22:42:57 2020]

Error in rule featureExtract_coarse:
    jobid: 53
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-19_sub-0086_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-19_sub-0086_registration.done

RuleException:
CalledProcessError in line 63 of /home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/.snakemake/scripts/tmpi_xw70wd.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk", line 63, in __rule_featureExtract_coarse
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
RuleException:
CalledProcessError in line 63 of /home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/.snakemake/scripts/tmpqvq36384.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk", line 63, in __rule_featureExtract_coarse
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/greydon/Documents/GitHub/Auto-afids/.snakemake/log/2020-07-26T224256.407952.snakemake.log
